### ISSUE TITLE
no communication to blinds

### ISSUE THREAD

**Issue by u20p17** [andyboeh/esphome-elero#14]
Hi all,
first of all thank you for all your efforts! I tried to use this esphome code for controlling my blinds, but up to now I couldn't make it work...

I am using a Az-Delivery ESP32-Wroom-32 board and the 'TECNOIOT 2pcs CC1101 868MHz Wireless Module Long Distance Transmission with Antenna' ([Link](https://www.amazon.de/gp/product/B07RH67FWV/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1)). I connected the board the following:

![image](https://github.com/user-attachments/assets/2d571002-cd8b-4cae-85b2-e0f06d956419)

![image](https://github.com/user-attachments/assets/802b172f-4219-42f7-8801-78a279d01db4)

**ESP32 <=> CC1101**
     3.3V <=> Vcc
     GND <=> GND
     GPIO16 <=> GDO0 
     GPIO17 <=> GDO2
     GPIO18 <=> SCLK
     GPIO19 <=> MISO
     GPIO23 <=> MOSI
     GPIO5 <=> CS

and i connected the coil spring to the ANT...

Then I took the following esphome code with the fake blind...

```
esphome:
  name: eleroesp32
  friendly_name: EleroEsp32

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eleroesp32 Fallback Hotspot"
    password: "xxxxxxxxxxx"    
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.89
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Uhrzeit von HA holen
time:
  - platform: homeassistant
    id: homeassistant_time

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

external_components:
  - source: github://andyboeh/esphome-elero

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

elero:
  cs_pin: GPIO05
  gdo0_pin: GPIO16
  freq0: 0x0c #7a 0c
  freq1: 0x71
  freq2: 0x21

cover:
  - platform: elero
    blind_address: 0xa831e5
    channel: 1
    remote_address: 0xf0d008
    name: Schlafzimmer
    open_duration: 25s
    close_duration: 22s

captive_portal:

sensor:
  - platform: uptime
    name: "Uptime Sensor"
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 30s
    id: wlan_signal 

switch:
  - platform: restart
    name: "Elero ESP Restart"
    
bluetooth_proxy:
  active: true
```

After flashing, i opened the log window and moved the blind with my MultiTel2, but I couldn't see any log message... What could be the issue? How can I further debug into it?

Thanks!

BR
