### ISSUE TITLE
Blinds Movement Issue

### ISSUE THREAD

**Issue by breinsp** [andyboeh/esphome-elero#15]
Hi,

I'm experiencing an issue where my blinds don't consistently open or close fully after a single command from the interface. There's roughly a 1/3 chance they will work as expected. Most of the time, the motor gives a short jerk and stops immediately. To get them to move completely, I have to send the command multiple times.

Any insights into what could be causing this?

Thanks in advance for your help!

Here is my config
```
substitutions:
  name: esphome-web-2f0414
  friendly_name: Blinds

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

api:

ota:
  platform: esphome

improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

esp32_improv:
  authorizer: none

web_server:

external_components:
  - source: github://andyboeh/esphome-elero
    refresh: 0s

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

elero:
  cs_pin: GPIO5
  gdo0_pin: GPIO17
  freq0: 0x7a
  freq1: 0x71
  freq2: 0x21

cover:
  - platform: elero
    blind_address: 0x8f740f
    channel: 1
    remote_address: 0x86ab10
    name: Balcony
    payload_1: 0x00
    payload_2: 0x04
    pck_inf1: 0x6a
    pck_inf2: 0x00
    hop: 0x00
  - platform: elero
    blind_address: 0xf83a0f
    channel: 2
    remote_address: 0x86ab10
    name: Living Room
    payload_1: 0x00
    payload_2: 0x04
    pck_inf1: 0x6a
    pck_inf2: 0x00
    hop: 0x00
  - platform: elero
    blind_address: 0x1b730f
    channel: 3
    remote_address: 0x86ab10
    name: Bedroom
    payload_1: 0x00
    payload_2: 0x04
    pck_inf1: 0x6a
    pck_inf2: 0x00
    hop: 0x00
```
