### ISSUE TITLE
[HELP] Compilation failing - Can't get it to work

### ISSUE THREAD

**Issue by Crafter-Y** [andyboeh/esphome-elero#19]
Hi there, 

idk what I am doing wrong, but I can't even get it to compile. I'm using esphome 2025.4.2 on HA OS on rapi5.

```yaml
external_components:
  - source: github://andyboeh/esphome-elero@main

esphome:
  name: b-rolladen-steuerung
  friendly_name: B Rolladen Steuerung

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"

ota:
  - platform: esphome
    password: "REDACTED"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "B-Rolladen-Steuerung"
    password: "REDACTED"

captive_portal:

spi:
  id: spi_bus
  clk_pin: GPIO4
  miso_pin: GPIO5
  mosi_pin: GPIO6

elero:
  cs_pin: GPIO7
  gdo0_pin: GPIO3
  freq0: 0x7a         # Frequenzregister 0 (Standard 0x7a für ~868,3 MHz)
  freq1: 0x71
  freq2: 0x21

```

```
INFO ESPHome 2025.4.2
INFO Reading configuration /config/esphome/bastian-rolladen-steuerung.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing b-rolladen-steuerung (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
|-- SPI @ 2.0.0
Compiling .pioenvs/b-rolladen-steuerung/src/esphome/components/elero/elero.cpp.o
Compiling .pioenvs/b-rolladen-steuerung/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/b-rolladen-steuerung/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/b-rolladen-steuerung/src/esphome/components/mdns/mdns_libretiny.cpp.o
src/esphome/components/elero/elero.cpp:4:10: fatal error: esphome/components/elero/cover/EleroCover.h: No such file or directory
 #include "esphome/components/elero/cover/EleroCover.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pioenvs/b-rolladen-steuerung/src/esphome/components/mdns/mdns_rp2040.cpp.o
*** [.pioenvs/b-rolladen-steuerung/src/esphome/components/elero/elero.cpp.o] Error 1
========================== [FAILED] Took 2.19 seconds ==========================
```

Some of the values in there may be made up by LLM, but this should not be the problem here

Cleaning build files does not change the error.

I think that it might have something to do with one of the 2025 esphome updates.
