### ISSUE TITLE
Lost in the jungle. Need some help.

### ISSUE THREAD

**Issue by Hufenbacke** [andyboeh/esphome-elero#7]
Hey guys,

I need some help. I just got some new Eleros and now I want to integrate them in Home Assistant. I don´t have a TempoTel2. I have MonoTec-868. On Eleros website they are listed as bidirectional.
I have to say that this is my first ESP32 project, so I lack some knowledge. So I have espHome setup in HomeAssistant. I was able to flash the firmware on the device and it is booting. So this seems to be working.
Than I tried to listen to the communication of the elero network. But this is where my problems begin. I don´t know where I should look. I guessed that it was this log:

![log](https://github.com/user-attachments/assets/f1ed7619-a7dd-4a37-b450-bfe2e9bc67d4)

But there happens nothing after pressing a button. The last entry in this log is: 
```
[21:33:59][C][safe_mode:018]: Safe Mode:
[21:33:59][C][safe_mode:020]:   Boot considered successful after 60 seconds
[21:33:59][C][safe_mode:021]:   Invoke after 10 boot attempts
[21:33:59][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[21:33:59][C][api:139]: API Server:
[21:33:59][C][api:140]:   Address: 10.20.20.80:6053
[21:33:59][C][api:142]:   Using noise encryption: YES
```

So do I have to look somewhere else or is this the right place. It is mentioned that I have to **enable logging**, but where do I do this? The log states the following:
```
[21:33:59][C][logger:185]: Logger:
[21:33:59][C][logger:186]:   Level: DEBUG
[21:33:59][C][logger:188]:   Log Baud Rate: 115200
[21:33:59][C][logger:189]:   Hardware UART: UART0
```

DEBUG sounds right to me. Or is it another option.

Here is my config so far:
```
esphome:
  name: elerosteuereinheit
  friendly_name: EleroSteuereinheit

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "******"

ota:
  - platform: esphome
    password: "*****"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 10.20.20.80
    gateway: 10.20.20.1
    subnet: 255.255.255.0
    dns1: 10.20.20.21
    dns2: 10.20.20.22

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Elerosteuereinheit"
    password: "****"

captive_portal:
    

external_components:
  - source: github://andyboeh/esphome-elero

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

elero:
  cs_pin: GPIO5
  gdo0_pin: GPIO26
  freq0: 0xc0
  freq1: 0x71
  freq2: 0x21

cover:
  - platform: elero
    blind_address: 0xa831e5
    channel: 4
    remote_address: 0xf0d008
    name: Schlafzimmer
    open_duration: 25s
    close_duration: 22s
    poll_interval: 120min
    supports_tilt: False
```

I used the blind from the default for the fake one. I hope that this was the right move.
